---
# Requires extra vars:
# - fullname
# - email

- hosts: localhost
  connection: local

  tasks:
    - name: setup .dotfiles
      get_url: url="https://raw.githubusercontent.com/nuada/ansible-dotfiles/master/files/{{ item }}" dest="{{ ansible_env.HOME }}/{{ item }}" force=yes
      with_items:
        - .bash_aliases
        - .bash_logout
        - .bash_profile
        - .bashrc
        - .gitconfig
        - .hgrc
        - .vimrc

    - name: set full name in hgrc
      lineinfile: dest="{{ ansible_env.HOME }}/.hgrc" regexp="^username =" line="username = {{ fullname }}"

    - name: set full name in gitconfig
      lineinfile: dest="{{ ansible_env.HOME }}/.gitconfig" regexp="^name =" line="name = {{ fullname }}"

    - name: set email in gitconfig
      lineinfile: dest="{{ ansible_env.HOME }}/.gitconfig" regexp="^email =" line="email = {{ email }}"

    - name: setup pathogen dirs
      file: path="{{ ansible_env.HOME }}/.vim/{{ item }}" state=directory
      with_items:
        - autoload
        - bundle

    - name: install pathogen
      get_url: url="https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim" dest="{{ ansible_env.HOME }}/.vim/autoload/pathogen.vim"

    - name: install plugins to pathogen bundle
      git: repo="git://github.com/{{ item }}.git" dest="{{ ansible_env.HOME }}/.vim/bundle/{{ item | basename }}" accept_hostkey=yes
      with_items:
        - avakhov/vim-yaml
        - chase/vim-ansible-yaml
        - godlygeek/tabular
        - tpope/vim-markdown
        - tpope/vim-sensible
